import { createRouteRegistry } from "@/platform/seo/route-registry";
import type { RouteDefinition } from "@/platform/seo/types";

import { seoConfig } from "./seo.config";

export const routeDefinitions = [
  {
    route: "/",
    class: "public_indexable",
    searchIntent: "evaluate a reusable SEO-first web product starter",
    primaryKeyword: "SEO-first web product starter",
    secondaryKeywords: ["next.js starter", "saas starter architecture"],
    title: "SEO-First Web Product Starter for Fast Launches",
    description:
      "Launch a focused SEO-first web product quickly with server-rendered landing pages, optional product modules, and secure foundations that stay off until you need them.",
    h1: "Launch an SEO-first web product on a safer foundation",
    pageType: "WebApplication",
    relatedRoutes: ["/seo-starter-checklist", "/pricing", "/privacy", "/terms"],
    lastModified: "2026-08-09",
    reviewStatus: "reviewed",
  },
  {
    route: "/seo-starter-checklist",
    class: "public_indexable",
    searchIntent: "use an SEO starter launch checklist for a new web product",
    primaryKeyword: "SEO starter launch checklist",
    secondaryKeywords: ["SEO launch checklist", "technical SEO starter"],
    title: "SEO Starter Launch Checklist for New Web Products",
    description:
      "Use a practical SEO starter launch checklist covering search intent, TDH, crawlability, internal links, structured data, Core Web Vitals, legal review, and release gates.",
    h1: "SEO starter launch checklist for a new web product",
    pageType: "Article",
    relatedRoutes: ["/", "/pricing", "/privacy"],
    lastModified: "2026-08-09",
    reviewStatus: "reviewed",
  },
  {
    route: "/pricing",
    class: "public_indexable",
    searchIntent: "understand a reusable web product pricing structure",
    primaryKeyword: "web product pricing template",
    secondaryKeywords: ["pricing page starter"],
    title: "Web Product Pricing Template and Structure",
    description:
      "Review a reusable web product pricing template with server-owned product configuration, clear commercial states, and optional monetization that can remain disabled at launch.",
    h1: "Web product pricing template and structure",
    pageType: "Pricing",
    relatedRoutes: ["/", "/seo-starter-checklist", "/refund-policy", "/terms"],
    lastModified: "2026-08-09",
    reviewStatus: "reviewed",
  },
  {
    route: "/privacy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Privacy Notice",
    description: "Project-configured privacy notice.",
  },
  {
    route: "/terms",
    class: "public_noindex",
    pageType: "Legal",
    title: "Terms of Service",
    description: "Project-configured terms of service.",
  },
  {
    route: "/acceptable-use",
    class: "public_noindex",
    pageType: "Legal",
    title: "Acceptable Use Policy",
    description: "Project-configured acceptable use policy.",
  },
  {
    route: "/refund-policy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Refund and Cancellation Policy",
    description: "Project-configured refund and cancellation policy.",
  },
  {
    route: "/contact",
    class: "public_noindex",
    pageType: "Legal",
    title: "Contact",
    description: "Project contact information.",
  },
  {
    route: "/account-deletion",
    class: "public_noindex",
    pageType: "Legal",
    title: "Account Deletion",
    description: "Account deletion instructions and lifecycle summary.",
  },
  { route: "/sign-in", class: "public_noindex" },
  { route: "/auth/magic-link/confirm", class: "public_noindex" },
  { route: "/account", class: "private" },
  { route: "/account/security", class: "private" },
  { route: "/account/billing", class: "private" },
  { route: "/account/credits", class: "private" },
  { route: "/account/deleted", class: "private" },
  { route: "/checkout/return", class: "private" },
  { route: "/robots.txt", class: "system" },
  { route: "/sitemap.xml", class: "system" },
  { route: "/api/auth", class: "system" },
  { route: "/api/auth/magic-link/request", class: "system" },
  { route: "/api/auth/magic-link/confirm", class: "system" },
  { route: "/api/account/delete", class: "system" },
  { route: "/api/commerce/checkout", class: "system" },
  { route: "/api/commerce/subscription/cancel", class: "system" },
  { route: "/api/commerce/subscription/resume", class: "system" },
  { route: "/api/commerce/refunds", class: "system" },
  { route: "/api/webhooks/waffo", class: "system" },
  { route: "/api/cron/account-deletions", class: "system" },
  { route: "/api/cron/commerce", class: "system" },
  { route: "/api/cron/credits", class: "system" },
  { route: "/api/test/emails/latest", class: "system" },
] as const satisfies readonly RouteDefinition[];

export const routeRegistry = createRouteRegistry(seoConfig, routeDefinitions);
